FROM ghcr.io/deck-app/nginx:v7.4
LABEL maintainer Naba Das <hello@get-deck.com>

RUN mkdir -p /app
RUN mkdir -p /var/preview
COPY default.conf /app/default.conf
COPY default.conf /etc/nginx/conf.d/default.conf
RUN wget -O /var/preview/index.html https://raw.githubusercontent.com/deck-app/stack-preview-screen/main/install/index.html

ARG SERVER_ROOT
RUN sed -i "s#{SERVER_ROOT}#/var/preview#g" /etc/nginx/conf.d/default.conf
RUN sed -i "s#{SERVER_ROOT}#/var/www/#g" /app/default.conf

# Persistent runtime dependencies
# Example RUN apk add --no-cache php7-openssl php7-sysvmsg php7-curl

WORKDIR /var/www

COPY php.ini /etc/php7/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php7/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php7/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php7-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php7/php.ini \
;fi

RUN apk add php7-zip
RUN apk add tar zip php7-gd php7-pdo php7-pdo_dblib php7-pdo_mysql php7-pdo_odbc php7-pdo_pgsql php7-pdo_sqlite php7-imap

COPY docker-entrypoint.sh /docker-entrypoint.sh
## Linux permission issue
ARG USER_ID
ARG GROUP_ID
RUN apk --no-cache add shadow unzip sudo
RUN usermod -u ${USER_ID} nobody && groupmod -g ${GROUP_ID} nobody

#Application Download
RUN curl -fLk -o /app/nextcloud.zip  "https://download.nextcloud.com/server/releases/nextcloud-24.0.2.zip"
RUN cd /app/ && unzip nextcloud.zip && rm nextcloud.zip 

# sudo command without password
RUN echo "nobody ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN sed -i "s#{BACK_END}#${BACK_END}#g" /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

## nobody permission issue
RUN usermod --home /home nobody
COPY www.conf /etc/php7/php-fpm.d/www.conf
COPY nginx.conf /etc/nginx/nginx.conf
RUN touch /env
RUN chown -R nobody:nobody /env
RUN chown -R nobody:nobody /home
RUN chown -R nobody:nobody /sbin/
RUN chown -R nobody:nobody /run/
RUN chown -R nobody:nobody /var/preview/
RUN chown -R nobody:nobody /etc/php7/
RUN chown -R nobody:nobody /etc/service/
RUN chown -R nobody:nobody /var/run/
RUN chown -R nobody:nobody /var/log/
RUN chown -R nobody:nobody /var/lib/nginx
RUN chown -R nobody:nobody /etc/nginx
USER nobody

CMD /docker-entrypoint.sh & /sbin/runit-wrapper